### ISSUE TITLE
[Design Proposal] Split master and client code

### ISSUE THREAD

**Issue by Hornwitser** [clusterio/factorioClusterio#214]
This is basically a extended version of #208.  The idea is to split up the codebase (but still keep it all in the same repository) such that it's easy to build a variant of it that only includes the master code, or only includes the slave code.  And to make it so that dependencies only needed by the master server does not get installed on slaves.

Essentially after this change the file structure will look something like
```
factorioClusterio/
+- CHANGELOG.m
+- README.md
+- LICENSE.md
+- lib/ - Code shared between master and slaves
|  +- package.json - Maybe put shared dependencies in here?
+- master/
|  +- package.json - master dependencies
|  +- config.json 
|  +- master.js
|  +- Dockerfile
|  +- static/
|  +- routes.js
|  +- routes/
|  +- database/
+- slave/
|  +- package.json - slave dependencies
|  +- config.json
|  +- client.js 
|  +- factorio/
|  +- instances/
+- sharedPlugins/
+- sharedMods/
+- scenarios/
+- CLI tools/ - Unsure about this one
```

And to for example build a master only variant you checkout out the code and then delete the slave directory.

Somewhat related to this I feel making the shared directories like this would be better.  It represents all the things that needs to be copied verbatim between all the slaves, maybe some kind of automatic syncing mechanism could be provided.
```
+- shared/
   +- plugins/
   +- mods/
   +- factorio/
   +- scenarios/
```

**Comment by Danielv123** [comment]
I like the idea of having a proper shared folder with subfolders instead of the mess we have now, but am not entirely sure if there are any benefits in splitting the code like that. We don't really have any issues with disk space usage, and it would require doing npm install twice etc.

We also need to figure out what we are going to do about our cli tools - currently, some of them are bundled in client.js, some like rcon are seperate files. I think I have a few more useful ones locally as well which I store in the CLI tools folder

**Comment by Hornwitser** [comment]
This has been implemented fully now with the code being put into separate packages.
