### ISSUE TITLE
Error starting master

### ISSUE THREAD

**Issue by stiny861** [clusterio/factorioClusterio#223]
I got an error message trying to start the master server using pm2. It says

TypeError: Cannot read property 'port' of null at startServer (/opt/factorioClusterio/master.js:944:73)

Any ideas?

**Comment by psihius** [comment]
Use 1.2.0 release and not master.
master is now 2.0 development version.

**Comment by Hornwitser** [comment]
For the record this error happens when the server was unable to bind to the port.  I already have a pr (#219) that fixes this to be more clear on what's going on.

There's also no instructions on how to use the 1.2.0 release.  If you're using to `git` (which is likely) you can switch to the `1.2.0` release by running `git checkout 1.2.0` on the command line.

**Comment by psihius** [comment]
README.md has been updated on how to set up the stable version of the Clusterio. Closing singe this is a setup issue for development version.
