### ISSUE TITLE
Allowed area restiction can be bypassed with Factorissimo2

### ISSUE THREAD

**Issue by Fank** [clusterio/factorioClusterio#259]
The default allowed area of 200 can be easily bypassed by placing a Factory and enter it, because the factory has there own coordinates and the center starts at 0,0

https://streamable.com/w9pcp

**Comment by Fank** [comment]
Maybe other mods are affected to which generate new "worlds"

**Comment by psihius** [comment]
Well, to be honest here, the mod compatibility details are not really the concern of the Clusterio core.
This should be done with plugins that will provide the compatibility layer to make it work with Clusterio, otherwise, we will have to handle every single plugin out there, keep the compatibility code up to date and that is just plain impossible with our small team of core devs.

This is really a job for a plugin.

**Comment by Hornwitser** [comment]
Eh, it's trival to check that surface isn't nauvis and don't allow placement.  What's more tricky is answering if there are surfaces other than nauvis that should be allowed.

**Comment by Fank** [comment]
I think a good way to go is to disable the placement outside of nauvis, and provide an option to enable it

**Comment by Danielv123** [comment]
Moved to https://github.com/clusterio/factorioClusterioMod/issues/57
