### ISSUE TITLE
[Design Proposal] Restructure and repack code

### ISSUE THREAD

**Issue by Hornwitser** [clusterio/factorioClusterio#316]
I've been thinking about this for some time now.  If we publish Clusterio and its plugins as packages on NPM it would solve the whole installing and updating process for both Clusterio and plugins.  The specifics that I had in mind was to use [Lerna](https://lerna.js.org/) in order to split the code into the packages: lib, master, slave, and ctl, under the npm org clusterio.

The basic idea is that these will be proper packages hosted on npm and that installation of clusterio will go through npm.  I.e., a working master server would be possible to bring up with `npm init && npm install @clusterio/master` followed by `npx clusterio-master run`.  This presuming of course that the master package exports a `clusterio-master` script.

File structure of the repository after this change would be similar to #214.  Something like this:

```
factorioClusterio/
+- CHANGELOG.md
+- README.md
+- LICENSE.md
+- lerna.json
+- packages/
|  +- lib/ - Code shared between master and slaves
|  |  +- package.json - lib dependencies
|  |  +- prometheus.js
|  |  +- link/
|  |  +- ...
|  +- master/
|  |  +- package.json - master dependencies
|  |  +- master.js
|  |  +- static/
|  |  +- routes.js
|  +- slave/
|  |  +- package.json - slave dependencies
|  |  +- config.json
|  |  +- slave.js
|  +- ctl/
|  |  +- package.json - clusterctl dependencies
|  |  +- clusterctl.js
|  +- plugin-global_chat/
|     +- package.json - global_chat's dependencies
|     +- info.js - Plugin definiton
|     +- ... plugin files.
+- sharedMods/
```

Plugins turned into npm packages will get usdependency resolution and installation for free which would also resolve #196.  This does necessitate the introduction of some kind of plugin array in the config that says which plugins have been installed as there's no easy way to figure out which npm packages are installed and compatible plugins from npm.  I am thinking plugin installation would be done with some kind of `add-plugin` command line tool which installs the package with npm and adds it to the necessary config array.

The separate web interface project would be able to pull `@clusterio/lib` directly as a regular npm dependency after this change.

-----

The second part of this proposal is changes to file and code conventions.  Starting with file conventions I would like for them to be switched over to `lower_case_underscore` for source files (except for build-mod.js) and directories in the source tree.  I just can't get over how ugly `luaTools.js` is compared to `lua_tools.js`.  But it also ties into the next suggestion I have, which is to have source files that contain a single class be named `CapitalClass`, like if for example `LineSplitter` in lib/factorio/server.js was pulled out into its own file it would be named `LineSplitter.js`.

Another thing I have noticed increasingly is that the shared stuff in `lib` is very generically named, and hard to avoid shadowing.  Like for example lib/plugin.  I'm thinking that if these were imported by convention to names starting with lib, it would avoid name clashes and make it a lot clearer where the modules come from.  For example:

```js
const libLink = require("@clusterio/lib/link");
const libPlugin = require("@clusterio/lib/plugin");
```

Lastly I want to split up the slave.js and master.js files into more modules, located in a src/ directory in their respective packages they are starting to get too long (over 1500 lines).  And then also move code in lib that isn't used anywhere else and highly unlikely to be used anywhere else into those src/ directories.  For example generateSSLcert.js is only ever used by the master server.

**Comment by psihius** [comment]
On the first read does sound reasonable, but I want to have some more time to ponder on this one and probably gonna have some questions (need to read up on some parts of this).

One of the questions is - how are we gonna handle the development environment? Having to work on dependencies that are in node_modules is a bad idea (and that's where NPM will stick them when installing). So, do we use git modules or what's the idea here? Cause we can organise the code in the repo in a sane manner as a tree and separate it. But when split into actual packages - it can become somewhat frustrating to work on the project where it's spread out via multiple packages. 
Library code is okay because it does a specific thing and usually does not change much on a day to day basis. But changing the master probably also requires changes in the slave code to match functionality and having those split between packages might just get frustrating to manage. It kind'a does not make sense for the size of the project we have. Better code organisation and not having files with 1500+ lines - yes. But I don't think we are at the size where we should split into packages in my opinion. Otherwise, we end up in the same situation as the whole JS/NodeJS ecosystem - shitloads of dependencies that are small.

But as I said, I'll do a think on this over the weekend.

**Comment by Hornwitser** [comment]
I can sort of answer the development side of this.  Lerna will link up the packages (with one command) so that they can run in their separate directories as if they were installed to node_modules, I'm still learning it and trying to set it up but this is far as I understand it.  The workflow shouldn't change much, changes to both slave and master can be done in the same commit as this will all still be in one repo.  The difference is that they will be publish on NPM as separate packages.

A big advantage that I've glossed over in the post, and one of the main reason I want to split this up into packages is so that you don't need to install a bunch of dependencies in places you're never going to use them.  For example the slaves doesn't need all the web server dependencies the master have, because they will never host a web server.  Another thing it does is make the separation between shared code, master code, and slave code much clearer.

**Comment by Danielv123** [comment]
Another advantage of lerna is that you can install plugins to both node_modules (using the wrapped npm install command) or git clone them into packages/ and use the plugins git repo for development. This way, plugins get full npm version control while still allowing development basically equal to core modules.

Personally I think multiple packages for plugins are basically a requirement. Most plugins will depend on the same packages as core or even core itself, so that won't be a big issue. But I expect there to be some plugins that pull in dependencies that would be just ridiculous to have in core, precisely due to the node ecosystem. Ex I know a module that gives simple excel export from react components - its multiple megabytes after minification. We don't want that in core. But we shouldn't prevent a simple statistics exporter plugin from using it either. I expect there will be similar situations with image manipulation libraries or something as well.

Another thing to keep in mind is new contributors. Maybe someone just wants to hack together a thing like we have seen with cluster wide auto pause plugins. Such plugins shouldn't have to follow the strict quality requirements we have for core, which would be awkward if they were to live in the same repo.

**Comment by Hornwitser** [comment]
One question though.  Do we want core plugins like research_sync and global_chat to live in a separate repository, or in this one along with lib/master/slave/ctl?

**Comment by Danielv123** [comment]
I think the current solution of having high quality plugins included in the default install makes sense. In 1.2.x, researchSync is in core since very few players don't want it, while stuff like playerManager and trainTeleports which can have undesired consequences and worse stability have been kept in separate repositories.

Although, with improved plugin installation and management we could still preserve the sensible default by including a few plugin install commands as an optional step of the setup.

**Comment by Hornwitser** [comment]
Finished up by #323 with an alpha pre-release published on npm today.
